#!/bin/bash

#Test script for lyric-based media search feature
# Verifies that Stage 2.5 (lyric media search) produces correctly tagged videos

set -e

echo "🧪 Integration Test: Lyric-Based Media Search"
echo "=============================================="
echo ""

# Setup test environment
TEST_DIR="outputs/test_lyric_search_$$"
mkdir -p "$TEST_DIR/media"
export OUTPUT_DIR="$TEST_DIR"

echo "📁 Test directory: $TEST_DIR"
echo ""

# Cleanup function
cleanup() {
    echo ""
    echo "🧹 Cleaning up test directory..."
    rm -rf "$TEST_DIR"
}
trap cleanup EXIT

# Step 1: Create mock lyrics.json
echo "Step 1: Creating mock lyrics data..."
cat > "$TEST_DIR/lyrics.json" << 'EOF'
{
  "lyrics": [
    {"line": "Molecules vibrate at high frequencies", "timestamp": 0.0},
    {"line": "Creating heat through kinetic energy", "timestamp": 3.0},
    {"line": "Atoms collide billions of times per second", "timestamp": 6.0}
  ],
  "full_text": "Molecules vibrate at high frequencies\nCreating heat through kinetic energy\nAtoms collide billions of times per second"
}
EOF
echo "  ✓ Created mock lyrics.json"

# Step 2: Create mock research.json (for topic context)
cat > "$TEST_DIR/research.json" << 'EOF'
{
  "topic": "How heat is generated at molecular level",
  "video_title": "Molecular Heat Generation Explained",
  "tone": "educational",
  "key_facts": [
    "Heat is generated by molecular vibration",
    "Molecules move faster when temperature increases"
  ]
}
EOF
echo "  ✓ Created mock research.json"
echo ""

# Step 3: Run lyric media search
echo "Step 2: Running lyric media search agent..."
if ./agents/3.5_lyric_media_search.sh; then
    echo "  ✓ Lyric media search completed"
else
    echo "  ✗ Lyric media search failed"
    exit 1
fi
echo ""

# Step 4: Verify output exists
echo "Step 3: Verifying output file..."
if [ ! -f "$TEST_DIR/lyric_media.json" ]; then
    echo "  ✗ FAILED: lyric_media.json not created"
    exit 1
fi
echo "  ✓ Output file created"
echo ""

# Step 5: Validate JSON structure
echo "Step 4: Validating JSON structure..."
python3 << EOF
import json
import sys

with open('$TEST_DIR/lyric_media.json') as f:
    data = json.load(f)

# Check required fields
required_fields = ['media_by_lyric', 'total_videos', 'lyric_coverage_percent', 'concepts_extracted']
missing = [f for f in required_fields if f not in data]
if missing:
    print(f"  ✗ FAILED: Missing fields: {missing}")
    sys.exit(1)

print(f"  ✓ All required fields present")

# Check media_by_lyric structure
if not data.get('media_by_lyric'):
    print("  ✗ FAILED: media_by_lyric is empty")
    sys.exit(1)

print(f"  ✓ Found {len(data['media_by_lyric'])} lyric entries")

# Verify lyric tagging
entry = data['media_by_lyric'][0]
required_entry_fields = ['lyric_line', 'visual_concept', 'search_term', 'videos']
missing_entry = [f for f in required_entry_fields if f not in entry]
if missing_entry:
    print(f"  ✗ FAILED: Entry missing fields: {missing_entry}")
    sys.exit(1)

print(f"  ✓ Lyric entries have correct structure")

# Verify video tagging
if entry['videos']:
    video = entry['videos'][0]
    required_video_fields = ['url', 'type', 'source', 'description']
    missing_video = [f for f in required_video_fields if f not in video]
    if missing_video:
        print(f"  ✗ FAILED: Video missing fields: {missing_video}")
        sys.exit(1)
    print(f"  ✓ Videos have correct structure")
else:
    print("  ⚠️  WARNING: No videos found (may indicate API issues)")

print(f"  ✓ Total videos found: {data['total_videos']}")
print(f"  ✓ Lyric coverage: {data['lyric_coverage_percent']}%")
print(f"  ✓ Concepts extracted: {data['concepts_extracted']}")
EOF

if [ $? -eq 0 ]; then
    echo "  ✓ JSON validation passed"
else
    echo "  ✗ JSON validation failed"
    exit 1
fi
echo ""

# Step 6: Test visual ranking integration
echo "Step 5: Testing visual ranking integration..."
if python3 agents/3_rank_visuals.py 2>&1 | grep -q "Loaded .* videos from lyric media search"; then
    echo "  ✓ Visual ranking successfully loads lyric media"
else
    echo "  ⚠️  WARNING: Visual ranking may not be loading lyric media correctly"
fi
echo ""

# Step 7: Verify lyric metadata preservation
echo "Step 6: Verifying lyric metadata preservation..."
python3 << EOF
import json
import sys

# Load visual rankings (if created)
try:
    with open('$TEST_DIR/visual_rankings.json') as f:
        rankings = json.load(f)

    # Check that ranked media preserves lyric tags
    if rankings.get('ranked_media'):
        video = rankings['ranked_media'][0]
        if 'lyric_line' in video and 'visual_concept' in video:
            print(f"  ✓ Lyric metadata preserved through ranking")
            print(f"    - lyric_line: {video.get('lyric_line', 'N/A')[:50]}...")
            print(f"    - visual_score: {video.get('visual_score', 'N/A')}")
        else:
            print("  ✗ FAILED: Lyric metadata not preserved")
            sys.exit(1)
    else:
        print("  ⚠️  No ranked media to verify (ranking may have been skipped)")
except FileNotFoundError:
    print("  ⚠️  Visual rankings not created (test may be incomplete)")
EOF
echo ""

echo "=============================================="
echo "✅ All tests passed!"
echo "=============================================="
echo ""
echo "Summary:"
echo "  • Lyric media search produces valid output"
echo "  • Videos are tagged with source lyric metadata"
echo "  • Integration with visual ranking works"
echo "  • Lyric metadata preserved through pipeline"
echo ""
